# Generated by Django 3.2.8 on 2022-06-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('customer_address', models.TextField()),
                ('customer_city', models.TextField()),
            ],
            options={
                'verbose_name': 'customer details',
                'verbose_name_plural': "customers' details",
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(verbose_name='device manufacturer')),
                ('model', models.TextField(verbose_name='device model')),
            ],
            options={
                'verbose_name': 'available devices',
                'verbose_name_plural': 'available devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField()),
                ('owner_status', models.TextField()),
                ('analyzer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_orders.device')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_orders.customer')),
            ],
            options={
                'db_table': 'devices_in_fields',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateField(blank=True, null=True)),
                ('order_status', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_orders.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_orders.deviceinfield')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
